### PR TITLE
WIP: get ImageCore working on 0.7

### PR DESCRIPTION
**Pull request by timholy**
This is a work-in-progress towards getting this package working again on 0.7. Having `showarg` move into Base is a good thing overall, but it requires a fair amount of refactoring. I thought I'd post now in case concerns arise, but before this can pass it needs the following PRs:
- [x] Disambiguations in Base, https://github.com/JuliaLang/julia/pull/22322
- [x] Fixes to inferrability in Base, https://github.com/JuliaLang/julia/pull/23867
- [x] Changes to ShowItLikeYouBuildIt, to gradually move towards relying on Base: https://github.com/JuliaArrays/ShowItLikeYouBuildIt.jl/pull/6
- [x] `showarg` support in https://github.com/JuliaMath/FixedPointNumbers.jl/pull/94
- [x] `showarg` support in https://github.com/JuliaGraphics/ColorTypes.jl/pull/99
- [x] `showarg` support in https://github.com/JuliaArrays/OffsetArrays.jl/pull/32

Update: now it just needs to not break 0.6 and then will be ready to go.

### CODE REVIEW

**Comment by timholy** [comment]
Now fixed for 0.6. 0.7 is increasingly looking like it will simply require a fork: the new `ReinterpretArray` is currently causing failures, but it also opens the way to not needing `ColorView` and `ChannelView` anymore (the new `reinterpret` can work with general `AbstractArray`s).

Since this takes a big step towards getting 0.7 working and doesn't break anything (other than deleting deprecated functionality), I'll merge this. Before tagging ImageAxes will need to be updated because some of the functions it "fleshes out" have been exported from this package (but only have deprecated definitions).

**Comment by Evizero** [comment]
I am a bit confused about how to adapt to this, since I relied on `ImageCore.showcoloranttype` for pretty printing. The `ColorTypes` version doesn't looks as nice.

```julia
julia> ColorTypes.showcoloranttype(STDOUT, RGB{N0f8})
ColorTypes.RGB{FixedPointNumbers.Normed{UInt8,8}}
```

how can I accomplish the following behaviour now:

```julia
julia> ImageCore.showcoloranttype(STDOUT, RGB{N0f8})
RGB{N0f8}
```

**Comment by timholy** [comment]
It's now `colorant_string_with_eltype` and lives in ColorTypes.jl. Now that `showarg` is in Base, I had to push functionality down to lower levels (which eliminated the type-piracy that this was doing formerly), but I think there was some difficulty keeping all the names.

Sorry about that. This was a pretty ugly transition, actually, since the version of `showarg` in Base is pretty different from one that used to live here :frowning:.

**Comment by Evizero** [comment]
Ah, perfect. That's what I was looking for. Thanks!

No need to apologize: πάντα χωρεῖ καὶ οὐδὲν μένει

**Pull request merged**
