### PR TITLE
Fix docs and tests

### PR DESCRIPTION
**Pull request by ViralBShah**
Needs https://github.com/JuliaTesting/ReferenceTests.jl/pull/132

### CODE REVIEW

**Comment by ViralBShah** [comment]
This isn't picking the right versions of everything to test with.

**Comment by ViralBShah** [comment]
@johnnychen94 @timholy I have disabled a few tests mainly due to formatting issues that I didn't yet get around to fixing. Also the Aqua `stale_deps` test was failing on BlockArrays and I couldn't figure out why so disabled that for now.

If you guys can help fix more of those, it will be nice. But I think even with these, it should be ok to tag this release, which will pave the way for the broad ecosystem upgrade to new versions.

**Comment by charleskawczynski** [comment]
Can we instead add Aqua and BlockArrays to a docs/testing environment, rather than adding it as a direct package dependency?

**Comment by ViralBShah** [comment]
Good point. Can you make a PR if you dont mind?

**Comment by charleskawczynski** [comment]
Opened https://github.com/JuliaImages/ImageCore.jl/pull/208, cc @ViralBShah. I think that may be all that's needed. If we just leave the compat entries there, will that still guide the test env?

**Pull request merged**
