### PR TITLE
Conditionally import fft functions (if version is larger 0.7-)

### LINKED ISSUE #56: FFTW dependency
I think ImageCore should (on the stable branch) not depend on the FFTW package:

```
julia> using Images
INFO: Precompiling module Images.
WARNING: --output requested, but no modules defined during run
WARNING: The call to compilecache failed to create a usable precompiled cache file for module FFTW. Got:
WARNING: Cache file "/Users/knopp/.julia/lib/v0.6/FFTW.ji" not found.
WARNING: eval from module Main to ImageCore:    
Expr(:call, Expr(:., :Base, :include_from_node1)::Any, "/Users/knopp/.julia/v0.6/FFTW/src/FFTW.jl")::Any
  ** incremental compilation may be broken for this module **

WARNING: --output requested, but no modules defined during run
```

ref https://github.com/JuliaMath/FFTW.jl/issues/45#issuecomment-336661303

### PR DESCRIPTION
**Pull request by tknopp**
may close #56. @timholy

### CODE REVIEW

**Comment by rsrock** [comment]
@timholy, any objection to merging this?  I just ran into this issue, and this PR fixes it.

**Comment by timholy** [comment]
In principle none, but I was worried about the universal test failures. I haven't had time to investigate for myself, but if you're satisfied then by all means merge.

**Comment by tknopp** [comment]
I was concerned as well but they also seem to be present on master.

**Comment by timholy** [comment]
The test failures are not present on master, they are a consequence of this PR. If someone wants to carry this forward and get it so it passes tests, we can do a retrospective release, but my attention is on 0.7.

**Comment by tknopp** [comment]
@timholy: Absolutely. Keep 0.6 environment stable (as is) and full focus on 0.7

**Pull request closed without merging**
